[project]
name = "northwind-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pip>=25.0.1",
    "psycopg2>=2.9.10",
    "sqlmodel>=0.0.22",
]
