
--
-- Postgres SQL Schema dump automatic generated by geni
--


-- TABLES 

CREATE TABLE categories (
 category_id smallint  NOT NULL,
 category_name character varying (15) NOT NULL,
 description text ,
 picture bytea 
);

CREATE TABLE customer_customer_demo (
 customer_id character  NOT NULL,
 customer_type_id character  NOT NULL
);

CREATE TABLE customer_demographics (
 customer_desc text ,
 customer_type_id character  NOT NULL
);

CREATE TABLE customers (
 address character varying (60),
 city character varying (15),
 company_name character varying (40) NOT NULL,
 contact_name character varying (30),
 contact_title character varying (30),
 country character varying (15),
 customer_id character  NOT NULL,
 fax character varying (24),
 phone character varying (24),
 postal_code character varying (10),
 region character varying (15)
);

CREATE TABLE employee_territories (
 employee_id smallint  NOT NULL,
 territory_id character varying (20) NOT NULL
);

CREATE TABLE employees (
 address character varying (60),
 birth_date date ,
 city character varying (15),
 country character varying (15),
 employee_id smallint  NOT NULL,
 extension character varying (4),
 first_name character varying (10) NOT NULL,
 hire_date date ,
 home_phone character varying (24),
 last_name character varying (20) NOT NULL,
 notes text ,
 photo bytea ,
 photo_path character varying (255),
 postal_code character varying (10),
 region character varying (15),
 reports_to smallint ,
 salary numeric ,
 title character varying (30),
 title_of_courtesy character varying (25)
);

CREATE TABLE order_details (
 discount real  NOT NULL,
 order_id smallint  NOT NULL,
 product_id smallint  NOT NULL,
 quantity smallint  NOT NULL,
 unit_price real  NOT NULL
);

CREATE TABLE orders (
 customer_id character ,
 employee_id smallint ,
 freight real ,
 order_date date ,
 order_id smallint  NOT NULL,
 required_date date ,
 ship_address character varying (60),
 ship_city character varying (15),
 ship_country character varying (15),
 ship_name character varying (40),
 ship_postal_code character varying (10),
 ship_region character varying (15),
 ship_via smallint ,
 shipped_date date 
);

CREATE TABLE products (
 category_id smallint ,
 discontinued integer  NOT NULL,
 product_id smallint  NOT NULL,
 product_name character varying (40) NOT NULL,
 quantity_per_unit character varying (20),
 reorder_level smallint ,
 supplier_id smallint ,
 unit_price real ,
 units_in_stock smallint ,
 units_on_order smallint 
);

CREATE TABLE region (
 region_description character  NOT NULL,
 region_id smallint  NOT NULL
);

CREATE TABLE schema_migrations (
 id character varying (255) NOT NULL
);

CREATE TABLE shippers (
 company_name character varying (40) NOT NULL,
 phone character varying (24),
 shipper_id smallint  NOT NULL
);

CREATE TABLE suppliers (
 address character varying (60),
 city character varying (15),
 company_name character varying (40) NOT NULL,
 contact_name character varying (30),
 contact_title character varying (30),
 country character varying (15),
 fax character varying (24),
 homepage text ,
 phone character varying (24),
 postal_code character varying (10),
 region character varying (15),
 supplier_id smallint  NOT NULL
);

CREATE TABLE territories (
 region_id smallint  NOT NULL,
 territory_description character  NOT NULL,
 territory_id character varying (20) NOT NULL
);

CREATE TABLE us_states (
 state_abbr character varying (2),
 state_id smallint  NOT NULL,
 state_name character varying (100),
 state_region character varying (50)
);

-- CONSTRAINTS 

ALTER TABLE categories ADD CONSTRAINT categories_pkey PRIMARY KEY (category_id);

ALTER TABLE customer_customer_demo ADD CONSTRAINT customer_customer_demo_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(customer_id);

ALTER TABLE customer_customer_demo ADD CONSTRAINT customer_customer_demo_customer_type_id_fkey FOREIGN KEY (customer_type_id) REFERENCES customer_demographics(customer_type_id);

ALTER TABLE customer_customer_demo ADD CONSTRAINT customer_customer_demo_pkey PRIMARY KEY (customer_id);

ALTER TABLE customer_customer_demo ADD CONSTRAINT customer_customer_demo_pkey PRIMARY KEY (customer_type_id);

ALTER TABLE customer_demographics ADD CONSTRAINT customer_demographics_pkey PRIMARY KEY (customer_type_id);

ALTER TABLE customers ADD CONSTRAINT customers_pkey PRIMARY KEY (customer_id);

ALTER TABLE employee_territories ADD CONSTRAINT employee_territories_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(employee_id);

ALTER TABLE employee_territories ADD CONSTRAINT employee_territories_pkey PRIMARY KEY (employee_id);

ALTER TABLE employee_territories ADD CONSTRAINT employee_territories_pkey PRIMARY KEY (territory_id);

ALTER TABLE employee_territories ADD CONSTRAINT employee_territories_territory_id_fkey FOREIGN KEY (territory_id) REFERENCES territories(territory_id);

ALTER TABLE employees ADD CONSTRAINT employees_pkey PRIMARY KEY (employee_id);

ALTER TABLE employees ADD CONSTRAINT employees_reports_to_fkey FOREIGN KEY (reports_to) REFERENCES employees(employee_id);

ALTER TABLE order_details ADD CONSTRAINT order_details_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(order_id);

ALTER TABLE order_details ADD CONSTRAINT order_details_pkey PRIMARY KEY (order_id);

ALTER TABLE order_details ADD CONSTRAINT order_details_pkey PRIMARY KEY (product_id);

ALTER TABLE order_details ADD CONSTRAINT order_details_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(product_id);

ALTER TABLE orders ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(customer_id);

ALTER TABLE orders ADD CONSTRAINT orders_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(employee_id);

ALTER TABLE orders ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);

ALTER TABLE orders ADD CONSTRAINT orders_ship_via_fkey FOREIGN KEY (ship_via) REFERENCES shippers(shipper_id);

ALTER TABLE products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(category_id);

ALTER TABLE products ADD CONSTRAINT products_pkey PRIMARY KEY (product_id);

ALTER TABLE products ADD CONSTRAINT products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id);

ALTER TABLE region ADD CONSTRAINT region_pkey PRIMARY KEY (region_id);

ALTER TABLE schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (id);

ALTER TABLE shippers ADD CONSTRAINT shippers_pkey PRIMARY KEY (shipper_id);

ALTER TABLE suppliers ADD CONSTRAINT suppliers_pkey PRIMARY KEY (supplier_id);

ALTER TABLE territories ADD CONSTRAINT territories_pkey PRIMARY KEY (territory_id);

ALTER TABLE territories ADD CONSTRAINT territories_region_id_fkey FOREIGN KEY (region_id) REFERENCES region(region_id);

ALTER TABLE us_states ADD CONSTRAINT us_states_pkey PRIMARY KEY (state_id);

-- INDEXES 

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (category_id)

CREATE UNIQUE INDEX customer_customer_demo_pkey ON public.customer_customer_demo USING btree (customer_id, customer_type_id)

CREATE UNIQUE INDEX customer_demographics_pkey ON public.customer_demographics USING btree (customer_type_id)

CREATE UNIQUE INDEX customers_pkey ON public.customers USING btree (customer_id)

CREATE UNIQUE INDEX employee_territories_pkey ON public.employee_territories USING btree (employee_id, territory_id)

CREATE UNIQUE INDEX employees_pkey ON public.employees USING btree (employee_id)

CREATE UNIQUE INDEX order_details_pkey ON public.order_details USING btree (order_id, product_id)

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (order_id)

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (product_id)

CREATE UNIQUE INDEX region_pkey ON public.region USING btree (region_id)

CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id)

CREATE UNIQUE INDEX shippers_pkey ON public.shippers USING btree (shipper_id)

CREATE UNIQUE INDEX suppliers_pkey ON public.suppliers USING btree (supplier_id)

CREATE UNIQUE INDEX territories_pkey ON public.territories USING btree (territory_id)

CREATE UNIQUE INDEX us_states_pkey ON public.us_states USING btree (state_id)

